### ISSUE TITLE
Move API off of root

### ISSUE THREAD

**Issue by raygesualdo** [3Blades/openresty#37]
Currently, one hit's the API at the root of the proxy (`/`). It seems it would be more correct to have it under an `/api` path. Additionally, it would seem best to include an API version number e.g. `/api/v1/...`.

**Comment by jgwerner** [comment]
cc/ @roachmd I agree that either:

1. We should have a dedicated API sub-domain, such as https://api.3blades.io
1. We should have a sub-directory, such as https://go.3blades.io/api

In either case, the API needs to have a version assigned to it:

1. https://api.3blades.io/v1
1. https://go.3blades.io/api/v1

**Comment by raygesualdo** [comment]
Dedicated subdomain may be the better call here. If we put the API on a subdomain, would you envision the server URLs being on that subdomain or the primary web app subdomain? I would argue it's better to keep them on the API subdomain so we keep routing consistent there and leave all routing on the web app subdomain to the web app itself. That way we don't run into any path name collisions. Thoughts?

**Comment by jkp85** [comment]
I also think subdomain is better.

**Comment by roachmd** [comment]
I feel a dedicated subdomain with version tag at the end makes provides better readability.

So for me choice 1.  I demo the idea with traefik before leaving my last position.

**Comment by jgwerner** [comment]
Agree. Dedicated sub-domain would be better long term to keep our layers decoupled.

**Comment by raygesualdo** [comment]
I'm going to close this as we now have the API on its own subdomain.
